// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDloX6U7uxv_gSNJQ2HN40OYiIJrK6iD34',
    appId: '1:374036422802:web:e29fc2cee7f23180ec464b',
    messagingSenderId: '374036422802',
    projectId: 'fasumpab2',
    authDomain: 'fasumpab2.firebaseapp.com',
    storageBucket: 'fasumpab2.firebasestorage.app',
    measurementId: 'G-ESHL56JJ6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtGL6bdIfzkZzXajGoquv7TztjNCEET6U',
    appId: '1:374036422802:android:e87d64723144b7a4ec464b',
    messagingSenderId: '374036422802',
    projectId: 'fasumpab2',
    storageBucket: 'fasumpab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQCjuA02SovtFkgxjQKE65x6sP3DUK8kA',
    appId: '1:374036422802:ios:ae37703438f08612ec464b',
    messagingSenderId: '374036422802',
    projectId: 'fasumpab2',
    storageBucket: 'fasumpab2.firebasestorage.app',
    iosBundleId: 'com.example.fasumpab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQCjuA02SovtFkgxjQKE65x6sP3DUK8kA',
    appId: '1:374036422802:ios:ae37703438f08612ec464b',
    messagingSenderId: '374036422802',
    projectId: 'fasumpab2',
    storageBucket: 'fasumpab2.firebasestorage.app',
    iosBundleId: 'com.example.fasumpab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDloX6U7uxv_gSNJQ2HN40OYiIJrK6iD34',
    appId: '1:374036422802:web:89691082f70838f8ec464b',
    messagingSenderId: '374036422802',
    projectId: 'fasumpab2',
    authDomain: 'fasumpab2.firebaseapp.com',
    storageBucket: 'fasumpab2.firebasestorage.app',
    measurementId: 'G-72EJCHBD4G',
  );
}
